[env:esp32cam]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = symlink://../../

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCAMERA_MODEL_AI_THINKER

board_build.partitions = huge_app.csv
